name: Deploy Page

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.WEBPAGESHH }}

    - name: Deploy files via SCP
      run: |
        # Check if the directory exists
        if [ -d "./website" ]; then
          scp -o StrictHostKeyChecking=no -r ./webpage/* root@43.204.206.207:/www/wwwroot/sameera.run.place
        else
          echo "Directory ./website does not exist."
          exit 1
        fi
